src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * User id from eternal twin, he should be unique
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $userId;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private string $displayName;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * One User has many decks. This is the inverse side.
     * @ORM\OneToMany(targetEntity="DeckDB", mappedBy="owner")
     *
     * @var Collection<DeckDB>
     */
    private Collection $decks;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private \DateTime $lastConnection;

    /* GAMEPLAY */

    public function __construct(string $userId, string $displayName)
    {
        $this->userId = $userId;
        $this->displayName = $displayName;
        $this->lastConnection = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?string
    {
        return $this->userId;
    }

    public function setUserId(string $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    public function setDisplayName(string $displayName): self
    {
        $this->displayName = $displayName;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return $this->displayName;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword() : ?string
    {
        // not needed for apps that do not check user passwords
        return null;
    }

    /**
     * @see UserInterface
     */
    public function getSalt() : ?string
    {
        // not needed for apps that do not check user passwords
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserIdentifier(): string
    {
        return $this->getUsername();
    }

    /**
     * @return \DateTime
     */
    public function getLastConnection(): \DateTime
    {
        return $this->lastConnection;
    }

    /**
     * @param \DateTime $lastConnection
     */
    public function setLastConnectionDate(\DateTime $lastConnection)
    {
        $this->lastConnection = $lastConnection;
    }

    /**
     * @return Collection<int, DeckDB>
     */
    public function getDecks(): Collection
    {
        return $this->decks;
    }

    public function findDeck(int $id): ?DeckDB
    {
        $result = null;

        /** @var DeckDB $deck */
        foreach ($this->decks as $deck) {
            if ($deck->getID() === $id) {
                $result = $deck;
                break;
            }
        }

        return $result;
    }

    public function hasAnyDeck(): bool
    {
        return count($this->decks) > 0;
    }

    public function getFirstDeck(): ?DeckDB
    {
        if ($this->hasAnyDeck()) {
            return $this->decks[0];
        }

        return null;
    }

    public function getPoints(): int
    {
        $result = 0;
        foreach ($this->decks as $deck) {
            $result += $deck->getLevel();
        }

        return $result;
    }
}

src/Controller/OnboardingController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Replay;
use App\Repository\UserRepository;
use App\Repository\ReplayRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OnboardingController extends AbstractController
{
    private ManagerRegistry $managerRegistry;

    /**
     * @param ManagerRegistry $managerRegistry
     */
    public function __construct(ManagerRegistry $managerRegistry)
    {
        $this->managerRegistry = $managerRegistry;
    }

    /**
     * @Route("/user/{id?}", name="user")
     *
     * @param int $id
     *
     * @return Response
     */
    public function user(?int $id): Response
    {
        /** @var UserRepository $userRepository */
        if ($userRepository = $this->managerRegistry->getRepository(User::class)) {
            $user = $id ? $userRepository->find($id) : $this->getUser();

            if($user) {
                return $this->render('Onboarding/user.html.twig', ['user' => $user]);
            }
        }

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/ranks/{page?1}", name="ranks")
     *
     * @return Response
     */
    public function leaderboard(int $page): Response
    {
        /** @var UserRepository $userRepository */
        if ($userRepository = $this->managerRegistry->getRepository(User::class)) {
            $users = $userRepository->findBy(array(), array(), 20, ($page-1) * 20);

            /** @var User $a */
            usort($users, fn($a, $b) => $a->getPoints() < $b->getPoints());

            // TODO Verify if we can directly get the value of page
            return $this->render('Onboarding/ranks.html.twig', ['users' => $users, 'page' => $page]);
        }

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/history/{id?}", name="history")
     *
     * @param int|null $id
     *
     * @return Response
     */
    public function history(?int $id): Response
    {
        /** @var UserRepository $userRepository */
        if ($userRepository = $this->managerRegistry->getRepository(User::class)) {
            $user = $id ? $userRepository->find($id) : $this->getUser();

            if ($user) {
                /** @var ReplayRepository $replayRepository */
                if ($replayRepository = $this->managerRegistry->getRepository(Replay::class)) {
                    $replays = $replayRepository->findBy(['firstOpponent' => $user], ['createdAt' => 'DESC'], 20, 0);

                    return $this->render('Onboarding/history.html.twig', ['replays' => $replays, 'user' => $user]);
                }
            }
        }

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/help")
     *
     * @return Response
     */
    public function help(): Response
    {
        return $this->render('Onboarding/help.html.twig');
    }
}

templates/Onboarding/history.html.twig
{# This means your page inherit from an existing template, it will already contains some html and allow to override what's inside the "blocks" #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {# Any extra CSS for your page #}
{% endblock %}

{% block javascripts %}
    {# Any extra JS for your page #}
{% endblock %}

{% block title %}
    - History
{% endblock %}

{% block content %}
    <table id="aTable">
        <tbody>
        <tr>
            <td class="mainBox">
                <h1 class="emc2">Historique des duels de {{ user.displayName }} </h1>
                <br/>
                {% for replay in replays %}
                    <div class="historique">
                        {% if replay.won %}
                            <img class="historyImg" alt="victory" src="{{ asset('img/gfx/icons/victory.jpg') }}"/>
                        {% else %}
                            <img class="historyImg" alt="looser" src="{{ asset('img/gfx/icons/looser.jpg') }}"/>
                        {% endif %}
                        <div class="duelHistory bright">
                            <h3>Le {{ replay.createdAt|date('Y-m-d H:i:s') }} -- [TODO: Info about the match]</h3>
                            {# <h3>Le {{ replay.createdAt|date('Y-m-d H:i:s') }} -- Motif Du Combat</h3> #}
                            <div class="duelHistoryBody">
                                <span class="packName">{{ replay.firstDeck.name }}</span>
                                {{ replay.won ? 'a défié et battu' : 'a défié mais a perdu contre' }}
                                le deck <span class="packName">{{ replay.secondDeck.name }}</span> de
                                <span class="userName"
                                      onmouseover="showTip(this,'Fiche joueur', 'Voir la fiche de {{ replay.secondOpponent.displayName }}.');"
                                      onmouseout="hideTip()">
                                    <a href="/user/{{ replay.secondOpponent.id }}">{{ replay.secondOpponent.displayName }}</a>
                                </span>
                                <img class="icon" alt="icon friend dinocard" src="http://data.dinocard.net/gfx/icons/friend.gif">
                                    {# TODO Friend feedback
                                     onmouseover="showTip(this,'Mes amis', 'Fait déjà partie de vos amis');"
                                     onmouseout="hideTip()">
                                     #}
                                .
                            </div>
                            <a href="{{ path('showReplay', {'id' : replay.firstDeck.id, 'otherId' : replay.secondDeck.id, 'seed' : replay.seed }) }}" class="button">
                                Revoir la partie
                            </a>
                        </div>
                    </div>
                {% else %}
                    <div>
                        Votre historique est vide. Créez un pack et affrontez d'autres joueurs dans l'arène...
                    </div>
                {% endfor %}
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/Onboarding/ranks.html.twig
{# This means your page inherit from an existing template, it will already contains some html and allow to override what's inside the "blocks" #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {# Any extra CSS for your page #}
{% endblock %}

{% block javascripts %}
    {# Any extra JS for your page #}
{% endblock %}

{% block title %}
    - Ranks
{% endblock %}

{% block content %}
    <table id="aTable">
        <tbody><tr>
            <td class="mainBox">
                <div id="msg">
                </div>

                <h1>Classement général</h1>

                <p class="txt">Le classement général est établi en fonction du <b>nombre de points</b> de chaque joueur.
                    Ce nombre est égal à la somme des niveaux des packs de chaque joueur. Ainsi un joueur ayant deux packs de niveau 3 (2x3 = 6pts) et un joueur ayant un pack de niveau 6 (1x6 = 6pts)
                    auront tous les deux le même nombre de points.</p>

                {#
                <p class="txt">Ce classement est mis à jour tous les jours aux alentours de 3 heures du matin. </p>
                <a href="/user/ranks" class="button">Classement général</a>&nbsp;<a href="/user/ranks?type=v" class="button">Classement des meilleurs packs</a>
                #}

                <div id="superTabRank">
                    <table>
                        <tbody>
                        <tr>
                            <th style="width:120px; text-align:center;">Position</th>
                            <th class="cardDesc">Joueur</th>
                            <th class="cardDesc">Points</th>
                            <th class="cardDesc">Nombre de packs</th>
                        </tr>


                        {% set rank = (page-1) * 20 + 1 %}
                        {% for user in users %}
                            {# TODO Css even/odd instead of this #}
                            <tr class="{{ rank % 2 == 0 ? 'even' : 'odd' }}">
                                <td style="width:120px;text-align:center;">
                                    <b>{{ rank }}</b>
                                </td>
                                <td style="text-align:center;"><a href="{{ path('user', {'id' : user.id }) }}">{{ user.displayName }}</a></td>
                                <td style="text-align:center;">
                                    <b>
                                        {{ user.points }} points
                                    </b>
                                </td>
                                <td style="text-align:center;">
                                    <b>
                                        {{ user.decks | length }} packs
                                    </b>
                                </td>
                            </tr>
                            {% set rank = rank + 1 %}
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <h3></h3>

                {% if page == 1 %}
                    Précédent
                {% else %}
                    <a href="{{ path('ranks', {'page' : page - 1 }) }}">Précédent</a>
                {% endif %}
                {#
                |
                <a href="#ranks/self">NYI Voir ma position</a>
                #}
                |
                {% if users | length > 0 and users | length < 20 %}
                    Suivant
                {% else %}
                    <a href="{{ path('ranks', {'page' : page + 1 }) }}">Suivant</a>
                {% endif %}
                {#
                <h3>Rechercher un joueur </h3>
                <form name="fsearchUser" id="fsearchUser" method="get" action="/user/ranks">
                    <input name="name" type="text" id="name" value="">
                    <input class="button" type="submit" value="Chercher !">
                </form>
                #}
            </td>

            <td class="siderBox">
                <img alt="classement dinocard" src="{{ asset('img/gfx/gui/artwork_ranking.jpg') }}">
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/Onboarding/user.html.twig
{# This means your page inherit from an existing template, it will already contains some html and allow to override what's inside the "blocks" #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {# Any extra CSS for your page #}
{% endblock %}

{% block javascripts %}
    {# Any extra JS for your page #}
{% endblock %}

{% block title %}
- User {{ user.displayName }}
{% endblock %}

{% set isOwner = user == app.user %}

{% block content %}
    <div id="msg">
    </div>
    <h1 class="emc2"> {{ user.displayName }} -
        <img alt="Classement" src="{{ asset('img/gfx/gui/ranking.gif') }}" title="Classement">
        #NYI ({{ user.points }} pts) &nbsp;
        {# Friend system
        <a href="/friend/add?id=489728" class="icon" onmouseover="showTip(this,'Mes amis', 'Ajouter à votre liste d\'amis ?');" onmouseout="hideTip()"><img class="icon" alt="icon friend dinocard" src="http://data.dinocard.net/gfx/icons/friend_add.gif"></a>
        #}
    </h1>

    {# Message System
    &nbsp;<a href="/mail/view?id=489728" class="button">Envoyer un message privé </a>
    #}
    {# Trade System
    &nbsp;<a href="/exchange/new?id=489728" class="button">Initier un nouvel échange</a>
    #}
    <div class="packArena">
        <div class="avatar">
            <div id="av867618"></div>
            <script type="text/javascript">
                //<![CDATA[
                {#
                var swf = new SWFObject('http://data.dinocard.net/swf/portrait.swf', 'game', 60, 84, 7, 'FFFFFF');
                swf.addVariable('url', 'http://data.dinocard.net/swf/avatar.swf');
                swf.addVariable('face', '4;0;5;10;1;0');
                swf.addVariable('flip', '2');
                swf.addParam('wmode', 'transparent');
                swf.addParam('menu', 'false');
                swf.write("av867618");
                //]]>
                #}
            </script>
        </div>

        {% for deck in user.decks %}
            <div class="pack">
                <div class="topBox">
                    <div class="levelBox">{{ deck.level }}</div>

                    <div class="packName">
                        <span class="packName"
                              onmouseover="showTip(this,'Deck', 'Voir le deck : {{ deck.name }}');"
                              onmouseout="hideTip()">
                            <a href="{{ path('showDeck', {'id' : deck.id })}}">{{ deck.name }}</a>
                        </span>
                        de
                        <span class="userName">
                            <a>{{ user.displayName }}</a>
                        </span>
                        <span>
                        </span>
                    </div>

                    <div class="packElements">
                        <img class="icon" alt="icon"
                             src="{{ asset('img/gfx/icons/element_unknown.gif') }}"
                             onmouseover="showTip(this,'Eléments inconnus', 'Vous ne pouvez pas encore voir les éléments majeurs de ce pack. Augmentez la compétence <b>Stratégie</b> de votre pack pour connaître les éléments joués par vos adversaires !');"
                             onmouseout="hideTip()">
                    </div>
                </div>

                <div class="leftBox">
                    <div class="victoryBox clickable"
                         onmouseover="showTip(this,'Pourcentage de victoire', 'Vous ne pouvez pas encore voir le pourcentage de victoire de ce pack. Augmentez votre compétence <b>Stratégie</b> pour cela.');"
                         onmouseout="hideTip()">
                        Victoire : ???
                        <div class="xpBorder">
                            <div class="xpBar" style="width : 0%;"></div>
                        </div>
                    </div>
                </div>

                <div class="middleBox">
                    <p class="smallTxt">
                    </p>
                </div>

                <div class="rightBox">
                    <div class="skillBox">
                        <span class="clickable"
                              onmouseover="showTip(this,'Points de vie', 'Vous ne pouvez pas encore voir les points de vie de ce pack. Augmentez votre compétence <b>Stratégie</b> pour cela.');"
                              onmouseout="hideTip()">
                            ?
                        </span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {# TODO player collection (not used)
    <a name="cards"></a>

    <div id="folderBox">
        <ul class="folders">
            <li class="active" id="folder1" onmouseover="showTip(this,'Echanges', 'Voir les cartes que le joueur propose à l\'échange.');" onmouseout="hideTip()">Echanges</li>
            <li class="disable" id="folder2" onmouseover="showTip(this,'Recherche', 'Voir les cartes que le joueur cherche à obtenir.');" onmouseout="hideTip()"><a href="/user/info?id=489728&amp;show=wanted">Recherche </a></li>
        </ul>
        <div id="boxContainer">
            <div id="filter">
                <form name="ffilter" id="ffilter" method="post" action="/user/info?id=489728#cards">
                    <input name="if" type="hidden" id="if" value="y">
                    <input name="id" type="hidden" id="id" value="489728">
                    <input name="reset" type="hidden" id="reset" value="">
                    <input name="sort" type="hidden" id="sort" value="element">
                    <input name="desc" type="hidden" id="desc" value="t">
                    <dl class="typeFilter">
                        <dt>Type </dt>
                        <dd>
                            <input name="dinoz" type="hidden" id="Dinoz" value="">
                            <a href="javascript:filterColSwap('Dinoz', '');" class="buttonDinoz" id="aDinoz" title="cartes dinoz"><span>dinoz</span></a>

                            <input name="spell" type="hidden" id="Spell" value="">
                            <a href="javascript:filterColSwap('Spell', '');" class="buttonSpell" id="aSpell" title="cartes incantations"><span>spell</span></a>

                            <input name="charm" type="hidden" id="Charm" value="">
                            <a href="javascript:filterColSwap('Charm', '');" class="buttonCharm" id="aCharm" title="cartes enchantements"><span>charm</span></a>

                            <input name="object" type="hidden" id="Object" value="">
                            <a href="javascript:filterColSwap('Object', '');" class="buttonObject" id="aObject" title="cartes objets magiques"><span>object</span></a>
                        </dd>
                    </dl>

                    <dl class="typeElement">
                        <dt>Elément </dt>
                        <dd>
                            <input name="fire" type="hidden" id="Fire" value="">
                            <a href="javascript:filterColSwap('Fire', '');" class="buttonFire" id="aFire" title="cartes feu"><span>fire</span></a>

                            <input name="water" type="hidden" id="Water" value="">
                            <a href="javascript:filterColSwap('Water', '');" class="buttonWater" id="aWater" title="cartes eau"><span>water</span></a>

                            <input name="wood" type="hidden" id="Wood" value="">
                            <a href="javascript:filterColSwap('Wood', ''); " class="buttonWood" id="aWood" title="cartes bois"><span>wood</span></a>

                            <input name="thunder" type="hidden" id="Thunder" value="">
                            <a href="javascript:filterColSwap('Thunder', ''); " class="buttonThunder" id="aThunder" title="cartes foudre"><span>thunder</span></a>

                            <input name="sky" type="hidden" id="Sky" value="">
                            <a href="javascript:filterColSwap('Sky', '');" class="buttonSky" id="aSky" title="cartes ciel"><span>sky</span></a>

                        </dd>
                    </dl>

                    <dl class="typeRarete">
                        <dt>Rareté </dt>
                        <dd>
                            <input name="common" type="hidden" id="Common" value="">
                            <a href="javascript:filterColSwap('Common', ''); " class="buttonCommon" id="aCommon" title="cartes communes"><span>common</span></a>

                            <input name="unco" type="hidden" id="Uncommon" value="">
                            <a href="javascript:filterColSwap('Uncommon', '');" class="buttonUncommon" id="aUncommon" title="cartes inhabituelles"><span>unco</span></a>

                            <input name="rare" type="hidden" id="Rare" value="">
                            <a href="javascript:filterColSwap('Rare', '');" class="buttonRare" id="aRare" title="cartes rares"><span>rare</span></a>
                        </dd>
                    </dl>

                    <dl class="typeEdition">
                        <dt>Edition </dt>
                        <dd>
                            <select name="ed" id="ed">
                                <option selected="selected" value="a">toutes</option>

                                <option value="1">Première édition</option>

                                <option value="2">Les portes d'Archélie</option>

                            </select>
                        </dd>
                    </dl>

                    <dl class="typeSearch">
                        <dt>Recherche </dt>
                        <dd><input name="search" type="text" id="search" value=""></dd>
                    </dl>
                    <dl class="filterButton">
                        <dt>&nbsp; </dt>
                        <dd>
                            <a href="javascript:document.getElementById('ffilter').submit();" class="button" onmouseover="showTip(this,'Filtrer', 'Applique les filtres sélectionnés.');" onmouseout="hideTip()">Filtrer</a>
                            <a href="javascript:resetInfo() ;" class="button" onmouseover="showTip(this,'Reset', 'Remise à zéro des filtres.<br />Affiche à nouveau toutes les cartes');" onmouseout="hideTip()">Reset</a>
                        </dd>

                    </dl>
                </form>
            </div>

            <div id="cardCollection">

            </div>

        </div>
    </div>
    #}
{% endblock %}