src/Challenge/Entity/Card.php
<?php

namespace App\Challenge\Entity;

use App\Challenge\Entity\EnergySystem\IEnergySource;
use App\Challenge\Enum\CardType;
use App\Challenge\Enum\ElementType;
use App\Challenge\Enum\Keyword;
use App\Challenge\Enum\RarityType;
use App\Service\Utils;

class Card implements IEnergySource
{
    /** @var int Unique identifier */
    private int $id;

    private CardType $type;
    private RarityType $rarity;

    private ElementType $element;

    /** @var array<CardCost> */
    private array $costs = [];

    // TODO Use it as a dictionnary<Keyword, count> for more efficiency
    /** @var array<Keyword>  */
    private array $keywords = [];

    /**
     * @var array<Effect> Each element of the array contains the json description of an effect
     */
    private array $effects = [];

    /** @var array Json that contains specific card data */
    private array $extraData;

    private ?Dinoz $dinoz = null;
    private ?Charm $charm = null;

    /**
     * @param int         $id
     * @param CardType    $cardType
     * @param ElementType $mainElement
     * @param RarityType  $rarityType
     */
    public function __construct(int $id, CardType $cardType, ElementType $mainElement, RarityType $rarityType)
    {
        $this->id = $id;
        $this->type = $cardType;
        $this->rarity = $rarityType;
        $this->element = $mainElement;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return CardType
     */
    public function getType(): CardType
    {
        return $this->type;
    }

    /**
     * @return RarityType
     */
    public function getRarity(): RarityType
    {
        return $this->rarity;
    }

    /**
     * @return ElementType
     */
    public function getElement(): ElementType
    {
        return $this->element;
    }

    /**
     * @return CardCost[]
     */
    public function getCosts(): array
    {
        return $this->costs;
    }

    /**
     * Note: This is used in TWIG to easily read costs in javascript
     * @return string
     */
    public function getCostsToString(): string
    {
        $costString = "";
        foreach ($this->costs as $cost) {
            $costString .= str_repeat($cost->getElement()->value.'/', $cost->getCount());
        }

        return $costString;
    }

    /**
     * @return string
     */
    public function getCostsAsImages(): string
    {
        $costsAsImagesString = "";
        foreach ($this->costs as $cost) {
            $costsAsImagesString .= sprintf('[%s %d]', Utils::getEnergyAsImage($cost->getElement()->value), $cost->getCount());
        }

        return $costsAsImagesString;
    }

    /**
     * @param CardCost $cost
     */
    public function addCost(CardCost $cost)
    {
        $this->costs[] = $cost;
    }

    /**
     * Returns the energy cost for the specified energy
     * @param ElementType $element
     *
     * @return int
     */
    public function getEnergyCost(ElementType $element): int
    {
        $cost = 0;
        foreach ($this->costs as $cardCost) {
            if ($element === $cardCost->getElement()) {
                $cost = $cardCost->getCount();
                break;
            }
        }
        return $cost;
    }

    /**
     * Count the energy cost for all energies types
     *
     * @return int
     */
    public function countCost(): int
    {
        $cost = 0;
        foreach (ElementType::cases() as $element) {
            $cost += $this->getEnergyCost($element);
        }
        return $cost;
    }

    /**
     * @return string[]
     */
    public function getKeywords(): array
    {
        return $this->keywords;
    }

    /**
     * @param Keyword $keyword
     */
    public function addKeyword(Keyword $keyword)
    {
        $this->keywords[] = $keyword;
    }

    /**
     * @param Keyword $keyword
     */
    public function removeKeyword(Keyword $keyword)
    {
        while (($key = array_search($keyword, $this->keywords, true)) !== false) {
            unset($this->keywords[$key]);
        }
    }

    /**
     * @param Keyword $keywordChecked
     *
     * @return bool
     */
    public function hasKeyword(Keyword $keywordChecked): bool
    {
        return in_array($keywordChecked, $this->keywords);
    }

    /**
     * @param Keyword $keywordChecked
     *
     * @return int
     */
    public function countKeyword(Keyword $keywordChecked): int
    {
        $count = 0;
        foreach ($this->keywords as $keyword) {
            if ($keyword === $keywordChecked) {
                $count++;
            }
        }

        return $count;
    }

    /**
     * @param int $initialHatchMarker
     */
    public function instantiateDinoz(int $initialHatchMarker = 0) : void
    {
        if (CardType::Dinoz === $this->getType()) {
            if (null === $this->dinoz) {
                if (count($this->extraData) !== 0) {
                    $this->dinoz = new Dinoz($this);
                    $this->dinoz->setHatchMarker($initialHatchMarker);
                }
            }
        }
    }

    /**
     * @return void
     */
    public function instantiateCharm() : void
    {
        if (CardType::Charm === $this->getType()) {
            if (null === $this->charm) {
                if (count($this->extraData) !== 0) {
                    $this->charm = new Charm($this);
                }
            }
        }
    }

    /**
     * @return Dinoz|null
     */
    public function getDinoz() : ?Dinoz
    {
        return $this->dinoz;
    }

    /**
     * @return Charm|null
     */
    public function getCharm() : ?Charm
    {
        return $this->charm;
    }

    /**
     * @return array
     */
    public function getExtraData(): array
    {
        return $this->extraData;
    }

    /**
     * @param array $extraData
     *
     * @return void
     */
    public function setExtraData(array $extraData)
    {
        $this->extraData = $extraData;
    }

    /**
     * IEnergySource implementation
     * @return ElementType
     */
    public function getEnergyElement(): ElementType
    {
        return $this->element;
    }

    /**
     * @return array
     */
    public function getEffects(): array
    {
        return $this->effects;
    }

    /**
     * @param array $effectData Effect Json Data
     *
     * @return void
     */
    public function addEffect(array $effectData)
    {
        $this->effects[] = new Effect($this, $effectData);
    }
}

templates/Card/card.html.twig
{% trans_default_domain 'Card' %}

{% if card is not null %}
    {# Card: MANDATORY #}
    {# ShowCard: MANDATORY Should we reveal the card? Or should we only see its back? #}
    {# Should we display an amount feedback? #}
    {% set amount = amount | default(1) %}
    {# Should we display a scaled down card that we can zoom? #}
    {% set canZoom = canZoom | default(false) %}
    {# Should we display the rarity feedback? #}
    {% set showRarity = showRarity | default(false) %}

    {% set cardId = card.id %}
    {% set cardElement = card.element.value %}
    {% set cardType = card.type.value %}

    {% set cardClassPrefix = cardType == "dinoz" ? "card_" : "card_spell_" %}

    {% if showCard %}
        {% set cardClass = cardClassPrefix~cardElement %}
    {% else %}
        {% set cardClass = cardClassPrefix~"back_"~cardElement %}
    {% endif %}

    <div class="{{ cardClass }} dinocard{% if canZoom%} zoomable{% endif%}">
        {% if showCard %}
            <div class="cardTop">
                <div class="cardName" id="name{{ cardId }}">{{ (cardId ~ '.name') | trans}}</div>
            </div>

            {% if showRarity %}
                <div class="cardRarity">
                    <img alt="common" src="{{ asset('img/gfx/icons/icon_' ~ card.rarity.value ~ '.gif') }}">
                </div>
            {% endif %}

            {% if cardId < 960 %}
                <img class="cardImg" src="{{ asset('img/gfx/card/artwork/' ~ cardId ~ '.jpg') }}" alt="artwork">
            {% else %}
                <img class="cardImg" src="{{ asset('img/gfx/card/artwork/none.jpg') }}" alt="no_artwork">
            {% endif %}

            <div class="mana">
                {% for cost in card.costs | reverse %}
                    {% for i in 0..cost.count - 1 %}
                        <img alt="{{ cost.element.value }}" src="{{ asset('img/gfx/icons/energy_' ~ cost.element.value ~ '.gif') }}">
                    {% endfor %}
                {% endfor %}
            </div>

            <div class="cardBody">
                <div class="cardTxt" id="desc{{ cardId }}">
                    <p>
                        {% for keyword in card.keywords %}
                            {% set keywordName = keyword.value %}
                            {% set name = ('capacities.' ~ keywordName ~ '.name') | trans %}
                            <span class="capacities"
                                  onmouseover="showTip(this,'{{ name }}', '{{ ('capacities.' ~ keywordName ~ '.tooltip') | trans }}');"
                                  onmouseout="hideTip()">
                                <b>{{ name }}</b>
                            </span>
                        {% endfor %}
                    </p>
                    <p>
                        {% if cardType != "dinoz" or card.effects | length > 0 %}
                            {{ (cardId ~ '.effects') | trans | raw }}
                        {% endif %}
                    </p>
                </div>

                <div class="cardFlavor">
                    <p>
                        {{ (cardId ~ '.lore') | trans | raw }}
                    </p>
                </div>

                {% if cardType == "dinoz" %}
                    {% set baseStrength = card.extraData["dinozStats"]["strength"] %}
                    {% set strength = strength | default(baseStrength) %}
                    {% set baseEndurance = card.extraData["dinozStats"]["endurance"] %}
                    {% set endurance = endurance | default(baseEndurance) %}
                    <div class="CardTurn">
                        {{ card.extraData["dinozStats"]["hatchTime"] }}
                    </div>

                    <div class="cardDef{% if baseEndurance != endurance %} statHighlight{% endif %}">
                        {{ endurance }}
                    </div>

                    <div class="cardAtk{% if baseStrength != strength %} statHighlight{% endif %}">
                        {{ strength }}
                    </div>
                {% else %}
                    <div class="CardTurn">
                        <img class="icon" alt="icon charm" src="{{ asset('img/gfx/icons/icon_small_' ~ cardType ~ '.gif') }}">
                    </div>
                {% endif %}
            </div>

            <div class="nbImages">
                <label id="ex_{{ cardId }}">
                    {% if amount > 1 %}
                        {# TODO Support amount above > 9 #}
                        <img class="icon" alt="xxx" src="{{ asset('img/gfx/font/x.gif') }}"><img alt="{{ amount }}" src="/img/gfx/font/{{ amount }}.gif"/>
                    {% endif %}
                </label>
            </div>

            <div class="cachecache" id="cache_{{ cardId }}">
                <label id="nb_{{ cardId }}">{{ amount }}</label>
                <label id="type_{{ cardId }}">{{ cardType }}</label>
                <label id="element_{{ cardId }}">{{ cardElement }}</label>
                <label id="rarity_{{ cardId }}">{{ card.rarity.value }}</label>
                <label id="energy_{{ cardId }}">{{ card.costsToString }}</label>
                {% if cardType == "dinoz" %}
                    <label id="atk_{{ cardId }}">{{ card.extraData["dinozStats"]["strength"] }}</label>
                    <label id="def_{{ cardId }}">{{ card.extraData["dinozStats"]["endurance"] }}</label>
                    <label id="ecl_{{ cardId }}">{{ card.extraData["dinozStats"]["hatchTime"] }}</label>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% else %}
    <img src="{{ asset('img/game/cards_back.gif') }}" alt="card back"/>
{% endif %}

templates/Card/collection.html.twig
{# This means your page inherit from an existing template, it will already contains some html and allow to override what's inside the "blocks" #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {# Any extra CSS for your page #}
{% endblock %}

{% block javascripts %}
    {# Any extra JS for your page #}
{% endblock %}

{% block title %}
- Collection
{% endblock %}

{% block content %}

{% endblock %}