src/Entity/DeckDB.php
<?php

namespace App\Entity;

use App\Repository\DeckRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DeckRepository::class)
 * @ORM\Table(name="deck")
 */
class DeckDB
{
    // TODO We need to identify easily the main element(s) of the decks

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * Many decks have one Owner. This is the owning side.
     * @ORM\ManyToOne(targetEntity="User", inversedBy="decks")
     */
    private User $owner;

    /**
     * @ORM\OneToMany(targetEntity="CardDB", mappedBy="deck", cascade={"persist", "remove"})
     *
     * @var Collection<CardDB>
     */
    private Collection $cards;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private string $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\Column(type="integer")
     */
    private int $victory = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private int $defeat = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private int $level = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private int $experience = 0;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $private = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private \DateTime $createdAt;

    // TODO DeckStats

    /**
     * @param User   $owner
     * @param string $name
     */
    public function __construct(User $owner, string $name)
    {
        $this->createdAt = new \DateTime();
        $this->cards = new ArrayCollection();
        $this->owner = $owner;
        $this->name = $name;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getOwner(): User
    {
        return $this->owner;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description ?: "";
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @return Collection<CardDB>
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    /**
     * @return int
     */
    public function getTotalCardsCount(): int
    {
        $count = 0;
        /** @var CardDB $card */
        foreach ($this->cards as $card) {
            $count += $card->getAmount();
        }

        return $count;
    }

    /**
     * @param CardDB $cardDB
     */
    public function addCard(CardDB $cardDB)
    {
        $this->cards->add($cardDB);
        $cardDB->setDeck($this);
    }

    /**
     * @param CardDB $cardDB
     */
    public function removeCard(CardDB $cardDB)
    {
        $this->cards->remove($cardDB);
    }

    /**
     * @return int
     */
    public function getLevel(): int
    {
        return $this->level;
    }

    /**
     * @return int
     */
    public function getExperience(): int
    {
        return $this->experience;
    }

    /**
     * @return bool
     */
    public function isPrivate(): bool
    {
        return $this->private;
    }

    /**
     * @param bool $private
     */
    public function setPrivate(bool $private): void
    {
        $this->private = $private;
    }

    /**
     * 
     */
    public function togglePrivate(): void
    {
        $this->private = !$this->private;
    }

    /**
     * @return float
     */
    public function getExperienceRatio(): float
    {
        // TODO Having a function that tells what is the nextLevel requirement.
        $nextLevel = 2 * $this->level;
        if ($nextLevel > 0) {
            return ($this->experience / $nextLevel) * 100.0;
        }

        return 0;
    }

    /**
     * @return int
     */
    public function getVictory(): int
    {
        return $this->victory;
    }

    /**
     * @return int
     */
    public function getDefeat(): int
    {
        return $this->defeat;
    }

    /**
     * @return float
     */
    public function getVictoryRatio(): float
    {
        $played = $this->victory + $this->defeat;
        if ($played > 0) {
            return ($this->victory / $played) * 100.0;
        }

        return 50;
    }
}

src/Controller/DeckController.php
<?php

namespace App\Controller;

use App\Entity\CardDB;
use App\Entity\DeckDB;
use App\Entity\User;
use App\Repository\DeckRepository;
use Doctrine\ORM\Cache\Exception\FeatureNotImplemented;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * API that allow player to interact with its deck.
 */
class DeckController extends AbstractController
{
    private ManagerRegistry $managerRegistry;

    public function __construct(ManagerRegistry $managerRegistry)
    {
        $this->managerRegistry = $managerRegistry;
    }

    /**
     * Show the specified deck
     *
     * @Route("/deck/show/{id}", name="showDeck")*
     *
     * @param int $id
     *
     * @return Response
     */
    public function showDeck(int $id): Response
    {
        $deckDb = $this->findOwnedDeck($id);
        if (null === $deckDb) {
            /** @var DeckRepository $deckRepository */
            $deckRepository = $this->managerRegistry->getManager()->getRepository(DeckDB::class);
            $deckDb = $deckRepository->find($id);
        }

        if (null !== $deckDb) {
            return $this->render('Deck/showDeck.html.twig', ['deckDB' => $deckDb]);
        }

        return $this->render('index.html.twig');
    }

    /**
     * @Route("/deck/new", name="newDeck")
     *
     * @return Response
     */
    public function newDeck(): Response
    {
        return $this->render('Deck/newDeck.html.twig');
    }

    /**
     * @Route("/deck/saveNew", name="saveNewDeck", methods={"POST"})
     *
     * @param Request $request
     *
     * @return Response
     */
    public function saveNewDeck(Request $request): Response
    {
        $payload = $request->request;

        /** @var User $user */
        if ($user = $this->getUser()) {
            $deckName = $payload->get('name');
            if ("" !== $deckName) {
                $deck = new DeckDB($user, $deckName);

                $deckCards = $payload->get('packCards');
                $cardsInfo = explode(' ', $deckCards);
                foreach ($cardsInfo as $cardInfo) {
                    $cardInfoArray = explode('#', $cardInfo);

                    $amount = min($cardInfoArray[1], 3);
                    $deck->addCard(new CardDB($cardInfoArray[0], $amount));
                }

                $this->managerRegistry->getManager()->persist($deck);
                $this->managerRegistry->getManager()->flush();

                return $this->redirectToRoute('showDeck', ['id' => $deck->getId()]);
            }
        }

        return $this->redirectToRoute('newDeck');
    }

    /**
     * @Route("/deck/edit/{id}", name="editDeck")
     *
     * @param int $id
     *
     * @return Response
     * @throws \Exception
     */
    public function editDeck(int $id): Response
    {
        throw new \Exception("Edit is not implemented");
    }

    /**
     * @Route("/deck/delete/{id}", name="deleteDeck", methods={"POST"})
     *
     * @param int $id
     *
     * @return Response
     */
    public function deleteDeck(int $id): Response
    {
        if ($deckDb = $this->findOwnedDeck($id)) {
            $this->managerRegistry->getManager()->remove($deckDb);
            $this->managerRegistry->getManager()->flush();
        }

        return $this->redirectToRoute('homepage');
    }

    /**
     * @param int $id
     *
     * @return DeckDB|null
     */
    private function findOwnedDeck(int $id): ?DeckDB
    {
        $result = null;
        /** @var User $user */
        if ($user = $this->getUser()) {
            if ($deck = $user->findDeck($id)) {
                $result = $deck;
            }
        }

        return $result;
    }

    /**
     * @Route("/deck/togglePrivate/{id}", name="togglePrivate")
     * 
     * @param int $id
     *
     * @return Response
     */
    public function togglePrivate($id): Response
    {
        if ($user = $this->getUser()) {
            if ($deck = $user->findDeck($id)) {
                $deck->togglePrivate();
                $this->managerRegistry->getManager()->flush();
            }
        }
        return $this->redirectToRoute('showDeck', ["id" => $id]);
    }
}

templates/Deck/newDeck.html.twig
{# This means your page inherit from an existing template, it will already contains some html and allow to override what's inside the "blocks" #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {# Any extra CSS for your page #}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/ihm.js') }}" type="application/javascript"></script>
    <script src="{{ asset('js/deck.js') }}" type="application/javascript"></script>
    <script src="{{ asset('js/cards.js') }}" type="application/javascript"></script>
{% endblock %}

{% block title %}
    - New Deck
{% endblock %}

{% block content %}
    <table id="aTable">
        <tbody>
        <tr>
            <td class="mainBox">
                <div id="msg">
                </div>

                <h1>Nouveau pack </h1>
                <form name="form" id="form" method="post" action="#user/switchCollectionView">
                    <input name="packCards" type="hidden" id="bonusCards" value=""/>
                </form>
                <div id="temp" style="display:none"></div>

                <div id="exchanges">
                    <div id="folderBox">
                        {#
                        <ul class="folders">
                            <li class="active" id="folder1">Cartes</li>
                            <li class="disable" id="folder2"><a href="javascript:submitView();">Tableau</a></li>
                        </ul>
                        #}
                        <div id="boxContainer">
                            {{ include('Components/filters.html.twig') }}

                            <div id="cardExchangeCollection">
                                {% for id in cardFactory.allCardId %}
                                    {% set card = cardFactory.loadCard(id) %}
                                    {% set maxAmount = 3 %}
                                    <div class="null clickable" onclick="addOneCard('{{ id }}', {{ maxAmount }});" id="card{{ card.id }}">
                                        {{ include('Card/card.html.twig', { 'card': card, 'showCard': true, 'amount': maxAmount }) }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </td>

            <td class="siderBox">
                <div id="rightMenu">
                    <div class="borderBrown">
                        <div class="borderWhite">
                            <h2>Nouveau pack </h2>

                            <p style="font-size : 11px; line-height : 10px;">
                                Cartes dans le pack :
                                <label id="nbCards">0</label>
                            </p>
                            <p>
                                <img alt="icon dinoz" src="{{ asset('img/gfx/icons/icon_small_dinoz.gif') }}"
                                     onmouseover="showHelp(this, 'nombre de dinoz dans le pack');"
                                     onmouseout="hideTip();"/>
                                <label id="dinozNb">0</label>
                                <img alt="icon spell" src="{{ asset('img/gfx/icons/icon_small_spell.gif') }}"
                                     onmouseover="showHelp(this, 'nombre d\'incantations dans le pack');"
                                     onmouseout="hideTip();"/>
                                <label id="spellNb">0</label>
                                <img alt="icon charm" src="{{ asset('img/gfx/icons/icon_small_charm.gif') }}"
                                     onmouseover="showHelp(this, 'nombre d\'enchantements dans le pack');"
                                     onmouseout="hideTip();"/>
                                <label id="itemNb">0</label>
                                <img alt="icon object" src="{{ asset('img/gfx/icons/icon_small_object.gif') }}"
                                     onmouseover="showHelp(this, 'nombre d\'objets magiques dans le pack');"
                                     onmouseout="hideTip();"/>
                                <label id="charmNb">0</label>
                            </p>
                            <div id="lockedCards">

                            </div>
                            <div id="listCards">
                                <ul>
                                    <li><i>Aucune carte ajoutée.</i></li>
                                </ul>
                            </div>

                            <form name="fNewPack" id="fNewPack" method="post" action="{{ path('saveNewDeck')}}">
                                <input name="name" type="hidden" id="name" value="new"> {# TODO for edition, change that to edit #}
                                <input name="view" type="hidden" id="view" value="true">
                                <input name="level" type="hidden" id="level" value="0">
                                <input name="packCards" type="hidden" id="pc" value="">
                                <p class="smallFont">Nom du pack : </p>
                                <input type="text" id="packSetName" style="width: 137px;" value="">
                            </form>
                            <br/>
                                <div class="buttonBox">
                                    <a class="button"
                                       onclick="saveDeck()"
                                       onmouseover="showTip(this,'Créer le pack', 'Sauvegarde de vos changements.');"
                                       onmouseout="hideTip()">
                                        Créer le pack
                                    </a>
                                    <a href="#deck/reset" class="button"
                                       onmouseover="showTip(this,'Vider', 'Remise à zéro de vos modifications.');"
                                       onmouseout="hideTip()">
                                        Vider
                                    </a>
                                </div>
                        </div>
                    </div>
                </div>

            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/Deck/showDeck.html.twig
{# This means your page inherit from an existing template, it will already contains some html and allow to override what's inside the "blocks" #}
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {# Any extra CSS for your page #}
{% endblock %}

{% block javascripts %}
    {# Any extra JS for your page #}
    <script src="{{ asset('js/ihm.js') }}" type="application/javascript"></script>
{% endblock %}

{% block title %}
    - Show Deck
{% endblock %}

{% set isOwner = app.user == deckDB.owner %}
{% set isPublic = not deckDB.private %}

{% block content %}
    {% if not isOwner %}
    <h1>Deck de
        <a href="{{ path('user', {'id' : deckDB.owner.id })}}">{{ deckDB.owner.displayName }}</a>
    </h1>
    {% endif %}

    <div id="msg">

    </div>

    <div id="rightMenu" style="float:right; position:relative;">
        {# TODO Implement ShowDeck RightMenu options
        <a href="{{ path('editDeck', { 'id' : deckDB.id }) }}" class="button"
           onmouseover="showTip(this,'Modifier les cartes', 'Cliquez ici pour ajouter des cartes à ce pack.');"
           onmouseout="hideTip()">
            Modifier les cartes
        </a>
        <a href="#duel/opponents" class="button"
           onmouseover="showTip(this,'Arène', 'Affrontez les autres joueurs pour gagner de l\'<b>expérience</b> et monter dans le classement !');"
           onmouseout="hideTip()">
            Arène
        </a>
        <a href="#duel/trOpponents?id=867665" class="button"
           onmouseover="showTip(this,'Défier un ami', '<strong>défis restants : 5</strong><br />vous disposez de 5 défis entre amis par jour.<br />  Défier un ami ne rapporte pas d\'expérience mais ne coûte pas de partie quotidienne.');"
           onmouseout="hideTip()">
            Défier un ami (5)
        </a>
        <a href="#duel/test" class="button"
           onmouseover="showTip(this,'Tester le pack', 'Un maître du Dojo que vous avez déjà battu est disponible chaque jour pour tester vos packs à l\'infini ! <br /><b>Tester un pack est illimité mais ne rapporte pas d\'expérience.</b>');"
           onmouseout="hideTip()">
            Tester le pack
        </a>    
        <a href="#duel/history?id=867665" class="button"
           onmouseover="showTip(this,'Historique', 'Voir l\'historique des combats de <b>DinocardPlus</b>.');"
           onmouseout="hideTip()">Historique</a>
        #}
        {% if isOwner %}
            <a href="{{ path('fightWithDeck', { 'id': deckDB.id }) }}" class="button"
               onmouseover="showTip(this,'Tester le Deck', 'Vous pouvez tester votre deck contre un deck généré aléatoirement. Cette action est illimité mais ne rapporte pas d\'expérience.</b>');"
               onmouseout="hideTip()">
                Tester le pack
            </a>
            <a href="javascript:requestDelete('fPackInfo', {{ deckDB.id }});" class="button"
               onmouseover="showTip(this, 'Dissoudre', 'Dissoudre ce pack vous permet de récupérer ses cartes pour créer de nouveaux packs ou faire des échanges. <br /><b>Attention : </b>Cette action est irréversible. Le niveau atteint par ce pack et ses points de compétences seront perdus.');"
               onmouseout="hideTip()">
                Dissoudre
            </a>
            {% if isPublic %}
                <a href="{{ path('togglePrivate', { 'id': deckDB.id }) }}" class="button"
                onmouseover="showTip(this,'Rendre le pack privé', 'Passer ce pack en privé, les autres joueurs ne pourront plus le visualiser.</b>');"
                onmouseout="hideTip()">
                    Rendre le pack privé
                </a>
            {% else %}
                <a href="{{ path('togglePrivate', { 'id': deckDB.id }) }}" class="button"
                onmouseover="showTip(this,'Rendre le pack public', 'Passer ce pack en public, les autres joueurs pourront de nouveau le visualiser.</b>');"
                onmouseout="hideTip()">
                    Rendre le pack public
                </a>
            {% endif %}
        {% else %}
            {% if app.user.hasAnyDeck %}
                <a href="{{ path('fightInArena', { 'id' : app.user.getFirstDeck.id, 'otherId' : deckDB.id }) }}" class="button"
                   onmouseover="showTip(this,'Combattre ce deck', 'Vous pouvez tester votre deck contre le deck de ce joueur. Cette action est illimité mais ne rapporte pas d\'expérience.</b>');"
                   onmouseout="hideTip()">
                    Combattre ce deck
                </a>
            {% endif %}
        {% endif %}
    </div>

    <form name="fPackInfo" id="fPackInfo" method="post">
        <input name="packId" type="hidden" value="{{ deckDB.id }}">
        {# What is that?
        <input name="downPack" type="hidden" id="downPack" value="867665">
        <input name="dir" type="hidden" value="info">
        #}
    </form>

    <div class="infoPack">
        <div class="avatar">
        </div>
        <div class="pack">
            <div class="topBox">
                <div class="levelBox">1</div>

                <div class="packName">
                    <span class="packName">{{ deckDB.name }}</span>
                    &nbsp; [ {{ deckDB.totalCardsCount }} cartes ] <span class="date"> créé le {{ deckDB.createdAt | date( 'd/m/Y à h:m:s', 'Europe/Paris' ) }}</span></div>
                <div class="packElements">
                    <img class="icon" alt="icon wood" src="{{ asset('img/gfx/icons/element_unknown.gif') }}"
                         onmouseover="showTip(this, 'Elément', 'TODO');"
                         onmouseout="hideTip()">
                </div>
            </div>

            <div class="leftBox">
                <div class="victoryBox">Victoire : {{ deckDB.victoryRatio }}%
                    <div class="xpBorder">
                        <div class="xpBar" style="width : {{ deckDB.victoryRatio }}% ;"></div>
                    </div>
                </div>
                <div class="xpBox">Expérience : {{ deckDB.experienceRatio }}%
                    <div class="xpBorder">
                        <div class="xpBar" style="width : {{ deckDB.experienceRatio }}% ;"></div>
                    </div>
                </div>
            </div>

            <div class="middleBox">
                <div class="smallTxt">Parties restantes</div>
                <img class="icon" alt="fight dinocard" src="http://data.dinocard.net/gfx/icons/fight.gif">
                <img class="icon" alt="fight dinocard" src="http://data.dinocard.net/gfx/icons/fight.gif">
            </div>

            <div class="rightBox">
                <div class="skillBox">
                    <span id="4" onmouseover="showTip(this,'Perception', 'Ce pack voit <b>3</b> adversaires dans l\'arène.<br />Chaque point en Perception vous permet de voir 2 adversaires de plus dans l\'arène.');"
                          onmouseout="hideTip()"> 0 </span>
                </div>
                <div class="skillBox">
                    <span id="3"
                          onmouseover="showTip(this,'Stratégie', 'La stratégie vous permet de voir des informations sur vos adversaires avant de les combattre. Leurs éléments majeurs, leurs points de vie.... jusqu\'à voir les cartes qu\'ils jouent.');"
                          onmouseout="hideTip()"> 0 </span>
                </div>
                <div class="skillBox">
                    <span id="1"
                          onmouseover="showTip(this,'Cartes bonus', 'Vous pouvez ajouter 1 carte à ce pack avant un combat, pour l\'adapter à la stratégie adverse. </div>');"
                          onmouseout="hideTip()"> 1 </span>
                </div>
                <div class="skillBox">
                    <span id="2"
                          onmouseover="showTip(this,'Points de vie', 'Ce pack commence ses duels avec 10 points de vie.');"
                          onmouseout="hideTip()"> 10 </span>
                </div>
            </div>
        </div>
    </div>

    {#
    <span class="smalltxt"
          onmouseover="showTip(this,'Description', 'La description de votre pack apparait aux autres joueurs, dans l\'arène ou sur votre fiche. La description est limitée à 220 caractères.');"
          onmouseout="hideTip()"> Description </span>
    <form name="fDescription" method="post" action="/pack/setDesc">
        <input name="packId" type="hidden" value="867665">

        <div class="packTxt">
            <textarea cols="60" name="desc" wrap="virtual" onkeyup="setPackDesc() ;" id="desc" rows="4">{{ deck.description }}</textarea>
        </div>
        <input class="button" type="submit" value="Valider">
    </form>
    #}

    <br>

    {% if isOwner or isPublic %}
        <div id="folderBox">
            {#
            <ul class="folders">
                <li class="active" id="folder1">Cartes</li>
                <li class="disable" id="folder2"><a href="/user/switchCollectionView">Tableau</a></li>
            </ul>
            #}
            <div id="boxContainer">
                <div id="cardCollection">
                    {% for cardDB in deckDB.cards %}
                        {{ include('Card/card.html.twig', { 'card': cardFactory.loadCard(cardDB.cardId), 'showCard': true, 'amount': cardDB.amount }) }}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <h2>Ce pack est actuellement privé, impossible de le voir pour le moment.
    </h2>
    {% endif %}
{% endblock %}